### ISSUE TITLE
Contribution Graph: Using locale for weekdays

### ISSUE THREAD

**Issue by ankraft** [xhacker/TEAChart#15]
The order of weekdays seems to be hard coded, where  the week always starts on Sunday. Would it be possible to change this in order to support locales where the week starts on Monday?
I guess one way to achieve this could be by adding 1 to the index (in case the week starts on Monday) and doing a modulus by 7 afterwards.
It would be great if this could be implemented.

**Comment by xhacker** [comment]
Good point. The first day should definitely be retrieved from `NSLocale`. However I don’t have time recently, if you made any changes, please pull request :)

**Comment by ankraft** [comment]
Please check the pull request #16. I also added support for localised names for the weekdays.

**Comment by ankraft** [comment]
Did you have a chance to look at PR #16 ?

**Comment by xhacker** [comment]
Closed via bb84675467935660da7d5bcda71a88894e3f8bf8.
