### ISSUE TITLE
fyi - did you consider adding strong / assign to properties? I get a lot of noise in xcode from this library

### ISSUE THREAD

**Issue by johndpope** [xhacker/TEAChart#17]
![screen shot 2016-06-21 at 4 15 28 pm](https://cloud.githubusercontent.com/assets/289994/16219703/74f0fef6-37cb-11e6-8192-adcf45562960.png)

**Comment by xhacker** [comment]
Can you make a pull request?

**Comment by xhacker** [comment]
I’m not seeing any warnings on my machine. What’s the compiler flags were you using?
