### ISSUE TITLE
View width is not eqaully splitting

### ISSUE THREAD

**Issue by ArunAshokan11** [xhacker/TEAChart#21]
![screen shot 2017-12-22 at 4 03 01 pm](https://user-images.githubusercontent.com/19771693/34295138-a2fdb836-e731-11e7-97ee-20ad05281d04.png)

This is my code..!

TEABarChart *barChart = [[TEABarChart alloc] initWithFrame:CGRectMake(0.0, 0.0, barView.frame.size.width, barView.frame.size.height)];
    barChart.barColors = @[[UIColor grayColor]];
    barChart.data = @[@2, @7, @1, @8, @2, @8, @10, @23];
    [barView addSubview:barChart];

i have given 8 values but showing 7 bars only

**Comment by xhacker** [comment]
Please attach a full sample project, thanks.
