### ISSUE TITLE
show data of selected days in contribution graph

### ISSUE THREAD

**Issue by deepakverma4** [xhacker/TEAChart#22]
how can we show data of selected days in contribution graph?
My code is like: 
```
- (NSInteger )valueForDay:(NSUInteger)day
{
    return 4;

}
```

which show 4 grade data for all the days (1-31) what if i want to show data for only 13th and 14th date? how to do that?

**Comment by deepakverma4** [comment]
@xhacker  can you please help me in solving this without any bounty?

**Comment by xhacker** [comment]
You should check what `day` is and return the corresponding value. For example, if it’s 13 or 14 return 4, otherwise return 0.

**Comment by dverma4u** [comment]
@xhacker i'm getting data to display in an NSArray. My code is : 

```
  NSArray *myData;
  
  myData = [NSArray arrayWithObjects: @"1", @"3", @"5", @"7", nil];
  
  for (int i = 0; i < [myData count]; i++) {
    if ([myData count] > 0) {
      if(day == myData[i]){
        NSLog(@"date in valueForDay %@ ", myData[i] );
      }
    }
  }
```

when i try to equate day with array elements that NSLog never get executed.
can you please tell me where i'm going wrong?
