### ISSUE TITLE
User interaction with contribution graph

### ISSUE THREAD

**Issue by kajensen** [xhacker/TEAChart#7]
It would be awesome to have a callback when a user selects a certain date in the contribution graph! A couple ideas: draw the calendar using subviews, or use a collectionview. both would be a major undertaking, though.

**Comment by mythodeia** [comment]
@kajensen have you found a solution for this. 
What i just tried is this:
- I added uibuttons on top of each rect
- used the runtime header to add custom info on each button by using the ```objc_setAssociatedObject``` call
- added an optional delegate to get the result back to the main view

**Comment by mythodeia** [comment]
check this https://github.com/xhacker/TEAChart/pull/11
