### ISSUE TITLE
Is it possible to use the contribution chart programmatically?

### ISSUE THREAD

**Issue by beheim** [xhacker/TEAChart#9]
Hello,

according to the docs Storyboard is supported so I was assuming programmatic approach should work too, but it is not explicitly stated.

If using programmatically it is currently not possible to use an own `delegate` because `loadDefaults()` will be invoked first thing in the `initWithFrame/-Coder`. So setting the delegate after that has no effect. 

As a workaround I am currently using plain `init` and I have exposed `loadDefaults` in the `.h`. 
It would be great if this is supported right away. Or am I missing something?

Love the charts!
Best,
Masa

**Comment by getaaron** [comment]
Looks like you're correct. Fortunately, `loadDefaults` appears to be idempotent, so you can simply call it again after setting the delegate. This isn't ideal, but it's a functional workaround.

As fixes, I'd suggest either:

1. Create an initializer like `initWithDelegate:frame:`, or 
2. Override `setDelegate:` to call `loadDefaults`.

**Comment by xhacker** [comment]
Thank you for the report!

@getaaron: I like the second idea. Will fix this tomorrow :)

**Comment by beheim** [comment]
I actually prefer both. Otherwise `loadDefaults` will be invoked twice when using `initWithFrame` and `setDelegate`, which is not necessary (especially for high number of grades).
And yes, `setDelegate` definitely needs to be there. This enables dynamically changing the grades/data.

@getaaron, @xhacker: Thank you!

**Comment by xhacker** [comment]
@beheim:
I'm a little confused. I tried to show the contribution graph programmatically, but finally got a black square. Can you tell me how to show it correctly?

Thanks!

**Comment by beheim** [comment]
@xhacker: I think you forgot to set the width and spacing. There are no defaults for that. (Maybe this can be added too.)

**Comment by getaaron** [comment]
:+1:

**Comment by beheim** [comment]
Thank you!
